name: iOS Build Tests

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: iOS Build Tests
    runs-on: macos-15

    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ secrets.GH_TOKEN }}

      - uses: actions/checkout@v4

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 16.4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler: '2.5.6'

      - name: Install Bundler
        run: gem install bundler

      - name: Install gems
        run: bundle install

      - name: Swift Packages Cache
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            Build/SourcePackages
            Build/Build/Products
          key: ${{ runner.os }}-deps-v1-${{ hashFiles('NeuroNote-UIKit.xcodeproj/project.xcshareddata/swiftpm/Package.resolved') }}
          restore-keys: ${{ runner.os }}-deps-v1-


      - name: Run Tests
        run: |
          if [ "${{ steps.cache.outputs.cache-hit }}" == 'true' ]; then
            bundle exec fastlane unit_test skip_package_dependencies_resolution:true
          else
            bundle exec fastlane unit_test
          fi